const mongoose = require('mongoose');

const itemSchema = new mongoose.Schema({
  name: { type: String, required: true },
  slug: { type: String, required: true },
  meta_desc: { type: String },
  image: { type: String },
  pin_image: { type: String },
  background: { type: String },
  meta_name: { type: String },
  address: { type: String },
  master_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, // reference to User
  city: { type: String, maxlength: 100 },
  allCity: { type: [String], default: [] },
  postal_code: { type: String },
  email: { type: String },
  mobile: { type: String },
  website: { type: String },
  logo: { type: String, default: '' },
  about_us: { type: String },
  lat: { type: Number, default: 0 },
  lng: { type: Number, default: 0 },
  storeLicence: { type: String },
  govtRegulationWebsite: { type: String },
  updatedAt: { type: Date },
  addedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  deletedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  updatedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  isDeleted: { type: Boolean, default: false },
  status: { type: String, enum: ['active', 'deactive'], default: 'active' },
  businessType: { type: String, default: '' },
  medical: { type: Boolean, default: false },
  recreational: { type: Boolean, default: false },
  recreation: { type: Boolean, default: false },
  isFeatured: { type: Boolean, default: false },
  isFeaturedDelivery: { type: Boolean, default: false },
  isMaster: { type: Boolean, default: false },
  userVisit: { type: Number, default: 0 },
  totalReviews: { type: Number, default: 0 },
  totalRating: { type: Number, default: 0.0 },
  scheduler: { type: [mongoose.Schema.Types.Mixed], default: [] },
  Type: { type: String },
  source: { type: String },
  fbUrl: { type: String, default: '' },
  instagramUrl: { type: String, default: '' },
  twitterUrl: { type: String, default: '' },
  gabUrl: { type: String, default: '' },
  deliveryFee: { type: Number, default: 0 },
  deliveryRadius: { type: Number, default: 0 },
  freeDeliveryOver: { type: Number, default: 0 },
  deliveryNotes: { type: String, default: '' },
  productStatus: { type: Boolean, default: false },
  commonCourier: { type: Boolean, default: false },
  nodeliveryfee: { type: Boolean, default: false },
  featureDispensary: { type: Boolean, default: false },
  analyticDashboard: { type: Boolean, default: false },
  reviewStatus: { type: Boolean, default: false },
  renewquarter: { type: Boolean, default: false },
  brandonfeaturedpage: { type: Boolean, default: false },
  bannerattop: { type: Boolean, default: false },
  introemail: { type: Boolean, default: false },
  reservedAhead: { type: Boolean, default: false },
  linkedInLiveMenus: { type: Boolean, default: false },
  featuredFrontpageWebApps: { type: Boolean, default: false },
  accessDashboard: { type: Boolean, default: false },
  editStoreDetails: { type: Boolean, default: false },
  isDelivery: { type: Boolean, default: false },
  isFeatureDelivery: { type: Boolean, default: false },
  isPinImage: { type: Boolean, default: false },
  client_id: { type: String, default: '' },
  client_secret: { type: String, default: '' },
  sevenPercentUpPrice: { type: Boolean, default: false },
  isOrderLimit: { type: Boolean, default: false },
  isOnSaleHide: { type: Boolean, default: false },
  orderLimit: { type: String, default: '' },
  instaleafCommision: { type: Number },
  oneHourDelivery: { type: Boolean, default: false },
  categorySetting: { type: mongoose.Schema.Types.Mixed },
}, { timestamps: true, versionKey: false });

module.exports = mongoose.model('Item', itemSchema);
