const mongoose = require("mongoose");

const ReserveOrderSchema = new mongoose.Schema(
  {
    order_number: { type: String },
    order_details: { type: Array },
    invoice_number: { type: String },
    deliveryTime: { type: String },
    totalprice: { type: Number, default: 0 },
    totalquanity: { type: Number, default: 0 },
    mobile: { type: String },
    countryCode: { type: String },
    shipping_address: { type: Array },
    billing_address: { type: Array },
    payment_status: { type: String, default: "Failed" },
    apartment: { type: String },
    payment_mode: { type: String },
    order_date: { type: Date },
    pickupDate: { type: Date },
    dispensary_id: { type: mongoose.Schema.Types.ObjectId, ref: "Item" },
    store_id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    addedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    dispensary_user_id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    driver: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    multipleAssignedDriver: { type: Array },
    multipleRejectedOrderDriver: { type: Array },
    order: { type: Number, default: 0 },
    tripBonus: { type: Number, default: 0 },
    driver_request_status: {
      type: String,
      enum: ["pending", "accepted", "declined"],
      default: "pending",
    },
    updated_by: { type: String },
    deleted_by: { type: String },
    driver_id: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
    assign_date: { type: String },
    driver_status: { type: String },
    transcation_id: { type: String },
    order_status: { type: String, default: "Pending" },
    order_delivered_date: { type: Date },
    pickupDateTime: { type: Date },
    status: { type: String, enum: ["active", "deactive"], default: "active" },
    isDeleted: { type: Boolean, default: false },
    isCancel: { type: Boolean, default: false },
    delivery_charge: { type: Number, default: 0 },
    gst: { type: Number, default: 0 },
    tip: { type: Number, default: 0 },
    puffski_margin: { type: Number, default: 0 },
    driver_margin: { type: Number, default: 0 },
    gross_margin: { type: Number, default: 0 },
    isRead: { type: Boolean, default: false },
    storeNotes: { type: String },
    deliveryNotes: { type: String },
    promoId: { type: mongoose.Schema.Types.ObjectId, ref: "PromoCodes" },
    express_Id: { type: String },
    senderName: { type: String },
    senderEmail: { type: String },
    senderPhone: { type: String },
    pickupAddress: { type: String },
    receiverName: { type: String },
    receiverEmail: { type: String },
    receiverPhone: { type: String },
    dropoffAddress: { type: String },
    city: { type: String },
    type: { type: String },
    productNames: { type: String },
  },
  { timestamps: true, versionKey: false } 
);

module.exports = mongoose.model("ReserveOrder", ReserveOrderSchema);
